
import { PurchaseRequisition, PRStatus } from '@/types/p2p';

export const mockPRs: PurchaseRequisition[] = [
  {
    id: 'PR-001',
    requester: {
      id: '2',
      name: 'John Requester',
      email: 'requester@example.com',
    },
    department: 'Marketing',
    costCenter: 'MKT-001',
    budgetCode: 'BUD-2023-MKT',
    status: PRStatus.APPROVED,
    dateCreated: '2023-09-15T10:30:00Z',
    dateNeeded: '2023-10-15T00:00:00Z',
    lineItems: [
      {
        id: 'PRLI-001-1',
        description: 'Office Desk - Premium',
        quantity: 5,
        unitPrice: 350,
        totalPrice: 1750,
        category: 'Furniture',
        deliveryDate: '2023-10-15T00:00:00Z',
      },
      {
        id: 'PRLI-001-2',
        description: 'Office Chair - Ergonomic',
        quantity: 5,
        unitPrice: 250,
        totalPrice: 1250,
        category: 'Furniture',
        deliveryDate: '2023-10-15T00:00:00Z',
      },
    ],
    justification: 'Required for new marketing team members',
    totalAmount: 3000,
    approvers: [
      {
        id: '3',
        name: 'Jane Approver',
        email: 'approver@example.com',
        status: 'APPROVED',
        comment: 'Approved as per budget allocation',
        date: '2023-09-17T14:20:00Z',
      },
    ],
    version: 1,
  },
  {
    id: 'PR-002',
    requester: {
      id: '2',
      name: 'John Requester',
      email: 'requester@example.com',
    },
    department: 'Marketing',
    costCenter: 'MKT-001',
    budgetCode: 'BUD-2023-MKT',
    status: PRStatus.PENDING_APPROVAL,
    dateCreated: '2023-09-20T09:15:00Z',
    dateNeeded: '2023-10-20T00:00:00Z',
    lineItems: [
      {
        id: 'PRLI-002-1',
        description: 'Marketing Brochures - High Quality Print',
        quantity: 1000,
        unitPrice: 2.5,
        totalPrice: 2500,
        category: 'Marketing Materials',
        deliveryDate: '2023-10-20T00:00:00Z',
      },
    ],
    justification: 'For upcoming trade show',
    totalAmount: 2500,
    approvers: [
      {
        id: '3',
        name: 'Jane Approver',
        email: 'approver@example.com',
        status: 'PENDING',
      },
    ],
    version: 1,
  },
  {
    id: 'PR-003',
    requester: {
      id: '2',
      name: 'John Requester',
      email: 'requester@example.com',
    },
    department: 'Marketing',
    costCenter: 'MKT-001',
    budgetCode: 'BUD-2023-MKT',
    status: PRStatus.DRAFT,
    dateCreated: '2023-09-22T14:10:00Z',
    dateNeeded: '2023-10-30T00:00:00Z',
    lineItems: [
      {
        id: 'PRLI-003-1',
        description: 'Digital Camera - Professional',
        quantity: 1,
        unitPrice: 1200,
        totalPrice: 1200,
        category: 'Electronics',
        deliveryDate: '2023-10-30T00:00:00Z',
      },
      {
        id: 'PRLI-003-2',
        description: 'Camera Tripod',
        quantity: 1,
        unitPrice: 150,
        totalPrice: 150,
        category: 'Electronics',
        deliveryDate: '2023-10-30T00:00:00Z',
      },
    ],
    justification: 'Needed for product photography',
    totalAmount: 1350,
    approvers: [],
    version: 1,
  },
  {
    id: 'PR-004',
    requester: {
      id: '2',
      name: 'John Requester',
      email: 'requester@example.com',
    },
    department: 'Marketing',
    costCenter: 'MKT-001',
    budgetCode: 'BUD-2023-MKT',
    status: PRStatus.REJECTED,
    dateCreated: '2023-09-10T11:20:00Z',
    dateNeeded: '2023-10-05T00:00:00Z',
    lineItems: [
      {
        id: 'PRLI-004-1',
        description: 'Premium Event Venue Booking',
        quantity: 1,
        unitPrice: 5000,
        totalPrice: 5000,
        category: 'Events',
        deliveryDate: '2023-10-05T00:00:00Z',
      },
    ],
    justification: 'For client appreciation event',
    totalAmount: 5000,
    approvers: [
      {
        id: '3',
        name: 'Jane Approver',
        email: 'approver@example.com',
        status: 'REJECTED',
        comment: 'Exceeds quarterly event budget. Please revise.',
        date: '2023-09-12T09:45:00Z',
      },
    ],
    version: 1,
  },
  {
    id: 'PR-005',
    requester: {
      id: '2',
      name: 'John Requester',
      email: 'requester@example.com',
    },
    department: 'Marketing',
    costCenter: 'MKT-001',
    budgetCode: 'BUD-2023-MKT',
    status: PRStatus.CONVERTED_TO_PO,
    dateCreated: '2023-09-05T08:30:00Z',
    dateNeeded: '2023-09-25T00:00:00Z',
    lineItems: [
      {
        id: 'PRLI-005-1',
        description: 'Company Branded Notebooks',
        quantity: 200,
        unitPrice: 15,
        totalPrice: 3000,
        category: 'Marketing Materials',
        deliveryDate: '2023-09-25T00:00:00Z',
      },
      {
        id: 'PRLI-005-2',
        description: 'Company Branded Pens',
        quantity: 500,
        unitPrice: 2,
        totalPrice: 1000,
        category: 'Marketing Materials',
        deliveryDate: '2023-09-25T00:00:00Z',
      },
    ],
    justification: 'For employee onboarding and client gifts',
    totalAmount: 4000,
    approvers: [
      {
        id: '3',
        name: 'Jane Approver',
        email: 'approver@example.com',
        status: 'APPROVED',
        comment: 'Approved as per marketing plan',
        date: '2023-09-07T10:15:00Z',
      },
    ],
    version: 1,
  },
];
