
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emlfifmbcuwfjrwaptnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbGZpZm1iY3V3Zmpyd2FwdG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTQ2MDUsImV4cCI6MjA1OTE3MDYwNX0.JWYErWrzyC_s6qfhgrvimQtIRwGL7pFkPiuqeLiCNXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
  }
});
